
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ✅ Import your shared components
import Header1 from "../components/mvpblocks/header-1";
import FooterGlow from "./components/Footer";
import FloatingBackground from "./FloatingBackground";

// ✅ Set up fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MatricsMind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <FloatingBackground />
        <Header1 /> {/* ✅ Visible on every page */}
        <main className="pt-24 px-4">{children}</main>
        <FooterGlow /> {/* ✅ Shared footer too */}
      </body>
    </html>
  );
}
